apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-project
  template:
    metadata:
      labels:
        app: kubernetes-project
    spec:
      containers:
        - name: kubernetes-project-container
          image: octovalents/kubernetes-project:1.0
          ports:
            - containerPort: 5000
