apiVersion: v1
kind: Service
metadata:
  name: kubernetes-project-service
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
